### ISSUE TITLE
Update all 3 new software laptops to driver station 2019

### ISSUE THREAD

**Issue by markmenge** [FRC1076/2019-Competition#11]
Prerequisites:
- Find national instruments install key/code from packet in Kit-Of-Parts (ask Solomon)
- Internet connection
- Label maker (business closet chest high, ask Matthew)
- Access to a new PC

Download the install from National Instruments. Google or look here:
https://wpilib.screenstepslive.com/s/currentCS/m/driver_station/l/144976-frc-driver-station-powered-by-ni-labview

After laptop is updated, print label that says:
"2019 Driver Station <date>"
Date is format: Feb 22,2019

**Comment by 2021GozonMarcusc** [comment]
It has been installed and the firewalls have been turned off
