### ISSUE TITLE
Transfer contents of software bill-of-materials to the team spreadsheet

### ISSUE THREAD

**Issue by mcolinj** [FRC1076/2019-Competition#13]
Need to mark the lines in our list as having been entered.    If we revise anything, we need to unmark them so it is clear that we need an update in the team spreadsheet.

Check slack channel for the team spreadsheet link.     Don't publish it in github, otherwise the rest of the world will be able to edit it and it will soon be filled with adverts.

**Comment by mcolinj** [comment]
Looks like we've done the transfer mostly.    Need to add the navx board to the list (we'll have one).
Also note that Kit of Parts items get excluded in the team spreadsheet, so some items that we might have added have been removed if they were in the kit of parts (proximity sensor, for example)

**Comment by juniormints2004** [comment]
I added the navx. This looks done!
