### ISSUE TITLE
Update all TalonSRXs to latest version of firmware 4.x

### ISSUE THREAD

**Issue by markmenge** [FRC1076/2019-Competition#18]
Update the TalonSRXs and TalonVictors to 4.x firmware level. I think Phoenix Tuner software needs to be installed first. (See #17)

**Comment by mcolinj** [comment]
Make sure to affix a label to every talon that gets software update.   Leave some whitespace on it so software can write CAN numbers on or some such.

**Comment by mcolinj** [comment]
I suspect the other motor controllers might require firmware upgrades as well?

**Comment by mcolinj** [comment]
On the practice electronics boards all of the talons and one victor had IDs assigned and firmware upgraded.   Seems that the victors do not play well with the talons on the CAN bus.    Not sure how to deal with that.      The most reliable way that I had to update all of the firmware was to have electrical folks wire up a single motor controller to the CAN bus and then assign the ID, name and update the firmware.      Stick to the ID assignment from the software requirements document.   https://github.com/FRC1076/2019-Competition/blob/master/mandatory-robot.txt
