### ISSUE TITLE
Implement Operator Controls

### ISSUE THREAD

**Issue by mcolinj** [FRC1076/2019-Competition#2]
Operator: Xbox Guitar Hero controller
1: Hatch Panel Low. 1+Whammy: Cargo Low
2: Hatch Panel Middle. 2+Whammy: Cargo Middle
3: Hatch Panel High. 3+Whammy: Cargo High
(1-3 elevator positions = 2 CIM motors in a toughbox gearbox)
4: Cargo intake IN. 4+Whammy: Cargo intake out (single motor tbd)
5: Hatch Panel grab (piston out). 5+Whammy: Hatch Panel release (piston in).
Whammy bar: Activate end game with Driver approval

4x Lv3 pistons extend with Driver's Start and Operator's Whammy activated simultaneously

Plan is to reset the encoder's position when the elevator is in the lowest position (i.e. floor cargo floor intake/hatch panel feeder station/Hatch Panel low place position) to minimize encoder drift using the prox switch from FIRST Choice.

Yes no autonomous, but this should be more than enough to keep you guys busy this season.

**Comment by mcolinj** [comment]
From Danniell:

Hey everybody! Let's start working on some driver controls. This year, we're going to attempt to use a guitar hero controller as the Operator in lieu of the normal Logitech.

**Comment by CharlieMonk** [comment]
1: Hatch Panel Low. 1+Wammy: Cargo Low (1, z!=0)
2: Hatch Panel Middle. 2+wammy: Cargo Middle (2, z!=0)
3: Hatch Panel High. 3+wammy: Cargo High (4, z!=0)
(1-3 elevator positions = 2 CIM motors in a toughbox gearbox)
4: Cargo intake IN. 4+wammy: Cargo intake out (single motor tbd) (3, z!=0)
5: Hatch Panel grab (piston out). 5+wammy: Hatch Panel release (piston in). (5, z!=0)
Start: Activate end game with Driver approval (8)
